// Generated by CoffeeScript 1.8.0
(function() {
  var AreaCtrl, ProductCtrl, async;

  ProductCtrl = require("./../control/productCtrl");

  AreaCtrl = require("./../control/areaCtrl");

  async = require("async");

  exports.product = function(req, res) {
    var id;
    id = req.params.id;
    return async.auto({
      getProduct: function(cb) {
        return ProductCtrl.detail(id, function(err, result) {
          var o, obj, price;
          if (err != null) {
            return cb(err);
          } else {
            price = (function() {
              var _i, _len, _ref, _results;
              _ref = result.price;
              _results = [];
              for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                o = _ref[_i];
                if (o.inventory > 0) {
                  _results.push({
                    id: o._id,
                    price: o.price,
                    inventory: o.inventory,
                    date: (o.date ? new Date(o.date).Format("yyyy-MM-dd") : ""),
                    spec: (o.spec ? o.spec.name : "")
                  });
                }
              }
              return _results;
            })();
            obj = {
              price: price,
              pid: result.product._id,
              name: result.product.name,
              productType: result.product.productType,
              content: result.product.content,
              image: result.product.images.length > 0 ? result.product.images[0].url : ""
            };
            return cb(null, obj);
          }
        });
      },
      getProvince: function(cb) {
        return AreaCtrl.provinceList(function(err, result) {
          if (err != null) {
            return cb(err);
          } else {
            if (result.error === 0) {
              return cb(null, result.data);
            } else {
              return cb(new Error("网络错误"));
            }
          }
        });
      }
    }, function(err, results) {
      var obj;
      obj = results.getProduct;
      obj.provinces = results.getProvince;
      if (err) {
        return res.render("500");
      } else {
        return res.render("qrScanProduct", obj);
      }
    });
  };

}).call(this);

//# sourceMappingURL=qrAction.js.map
