// Generated by CoffeeScript 1.8.0
(function() {
  var NewsCtrl;

  NewsCtrl = (function() {
    var config, request;

    function NewsCtrl() {}

    request = require("request");

    config = require("./../config/config.json");

    NewsCtrl.list = function(page, pageSize, ent, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/api/news/list?ent=" + ent + "&page=" + page + "&pageSize=" + pageSize;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        return fn(err, body ? JSON.parse(body) : {});
      });
    };

    NewsCtrl.detail = function(id, fn) {
      var url;
      url = "" + config.inf.host + ":" + config.inf.port + "/api/news/detail?id=" + id;
      return request({
        url: url,
        timeout: 3000
      }, function(err, response, body) {
        return fn(err, body ? JSON.parse(body) : {});
      });
    };

    return NewsCtrl;

  })();

  module.exports = NewsCtrl;

}).call(this);

//# sourceMappingURL=newsCtrl.js.map
